### ISSUE TITLE
Header: Phone number is not dynamic.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Dentistry-by-Design#11]
In the screenshot below, I change the phone number as for example, i change the last digit. Phone number in the header did not change, only in contacts page.
I also remove the phone number same thing happen, it was removed in contact page but the phone number in header was not removed.

![image](https://cloud.githubusercontent.com/assets/20430259/17655178/9a175a94-62dd-11e6-815b-38dbc51e5a9d.png)

**Comment by emmixaustralia** [comment]
Resolved
