### ISSUE TITLE
FAQ: why is it accordion title has bigger font size compare to the section title? 

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Dentistry-by-Design#12]
![image](https://cloud.githubusercontent.com/assets/20430259/17657065/0aafe4fa-62f3-11e6-988d-af3ba4ba6a89.png)

**Comment by emmixaustralia** [comment]
The title "ORAL HYGIENE" is a smaller font because it is made in all caps and has a different visual style. If we made it the same size, or larger, because it is all capitalized, it will actually look far too big.
