### ISSUE TITLE
Banner/inner banner: Image is cut at some point.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Dentistry-by-Design#20]
![image](https://cloud.githubusercontent.com/assets/20430259/17656753/0452ba2c-62f0-11e6-9079-ac0702ecbf30.png)

**Comment by emmixaustralia** [comment]
This item has been done on purpose, so we can show more of the height of the image on a mobile view. We've only cut parts that are not important to the main image.

**Comment by emmixaustralia** [comment]
Awaiting further feedback if required.
