### ISSUE TITLE
Admin - Options: No specific description in all custom fields.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Dentistry-by-Design#3]
Link:  http://dentistrybydesign-imp.stage.titanweb.com.au/wp-admin/admin.php?page=acf-options

![image](https://cloud.githubusercontent.com/assets/20430259/17654092/b12be3f0-62d1-11e6-9d01-8c4b6324a3e5.png)

**Comment by emmixaustralia** [comment]
Descriptions added, resolved.
