### ISSUE TITLE
Sitemap and Privacy Policy: Is there no need for a sitemap and a privacy in this new build?

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Dentistry-by-Design#8]
![image](https://cloud.githubusercontent.com/assets/20430259/17657166/b0b1f74e-62f3-11e6-8b36-ce8a5e528f05.png)

**Comment by emmixaustralia** [comment]
Existing client site didn't have any content for sitemap or Privacy. Let me know if it's required and send along any content - thank you.
