### ISSUE TITLE
Services: Posts are not align. Height should adjust base on the longest post title

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Dentistry-by-Design#9]
![image](https://cloud.githubusercontent.com/assets/20430259/17654667/2cb7fa30-62d8-11e6-944b-e05374410b49.png)

**Comment by emmixaustralia** [comment]
Sorry, we didn't imagine such a long title for a Service item. It is being fixed now.

**Comment by emmixaustralia** [comment]
Resolved
